# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 045e84e316766f63a295d5e9f28e6a22abf532a9b061264b25ca637120d2a48d69ad36ed293ea0be6acd7a56fcbfd55f9bf85d25f4349de2eabf1381fdd13822

test:
  secret_key_base: 0db4fa728c3c3662c17883fc6e46a513f6d6656f7b1916ea52136bfe5791514f80bd0c420eb14bfecd8a17dcbef2e527080c47ab30546a5d606ed96db8a841dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
